import csv
import io
from datetime import datetime
from uuid import uuid4

import pymupdf
from django.utils import timezone

from .analytics import CATEGORIES, build_session_analytics
from .models import ClassroomSession


PAGE_WIDTH = 842
PAGE_HEIGHT = 595
MARGIN = 42
NAVY = (29 / 255, 42 / 255, 59 / 255)
BRAND = (70 / 255, 95 / 255, 241 / 255)
MUTED = (100 / 255, 116 / 255, 139 / 255)
LIGHT = (241 / 255, 245 / 255, 249 / 255)
WHITE = (1, 1, 1)
CATEGORY_COLORS = {
    'engaged': (45 / 255, 60 / 255, 200 / 255),
    'attentive': (16 / 255, 185 / 255, 129 / 255),
    'confused': (245 / 255, 158 / 255, 11 / 255),
    'bored': (249 / 255, 115 / 255, 22 / 255),
    'disengaged': (239 / 255, 71 / 255, 111 / 255),
}


def _previous_session(session):
    return (
        ClassroomSession.objects.filter(
            subject=session.subject,
            started_at__lt=session.started_at,
        )
        .order_by('-started_at')
        .first()
    )


def _duration(seconds):
    minutes, remaining = divmod(max(0, round(seconds)), 60)
    hours, minutes = divmod(minutes, 60)
    return f'{hours}h {minutes}m' if hours else f'{minutes}:{remaining:02d}'


def _percent(value):
    return f'{value:.1f}%' if value is not None else 'N/A'


def _safe_csv_value(value):
    text = str(value)
    return f"'{text}" if text.startswith(('=', '+', '-', '@')) else text


def analytics_csv_content(analytics):
    output = io.StringIO(newline='')
    writer = csv.writer(output)
    writer.writerow([
        'Slide', 'Topic', 'Timestamp', 'Duration Seconds', 'Detected', 'Unclassified',
        'Engaged %', 'Attentive %', 'Confused %', 'Bored %',
        'Disengaged %', 'Average Confidence %',
    ])
    for slide in analytics['slides']:
        writer.writerow([
            slide['slide_number'],
            _safe_csv_value(slide['title']),
            slide['entered_at'],
            slide['duration_seconds'],
            slide['detected'],
            slide['unclassified'],
            slide['engaged'] if slide['engaged'] is not None else '',
            slide['attentive'] if slide['attentive'] is not None else '',
            slide['confused'] if slide['confused'] is not None else '',
            slide['bored'] if slide['bored'] is not None else '',
            slide['disengaged'] if slide['disengaged'] is not None else '',
            slide['average_confidence'] if slide['average_confidence'] is not None else '',
        ])
    return output.getvalue()


def _header(document, subtitle):
    page = document.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
    page.draw_rect(pymupdf.Rect(0, 0, PAGE_WIDTH, 82), color=NAVY, fill=NAVY)
    page.insert_text((MARGIN, 34), 'TAGAD', fontsize=22, fontname='hebo', color=WHITE)
    page.insert_text((MARGIN, 58), subtitle, fontsize=10, color=(0.78, 0.83, 0.91))
    page.insert_text((PAGE_WIDTH - 185, 45), 'CLASSROOM ANALYTICS', fontsize=9, color=WHITE)
    return page


def _section_title(page, y, title):
    page.insert_text((MARGIN, y), title, fontsize=12, fontname='hebo', color=NAVY)
    page.draw_line((MARGIN, y + 7), (PAGE_WIDTH - MARGIN, y + 7), color=(0.88, 0.9, 0.94))


def _summary_card(page, x, y, width, label, value, note=''):
    page.draw_rect(pymupdf.Rect(x, y, x + width, y + 62), color=(0.9, 0.92, 0.96), fill=(0.98, 0.985, 1))
    page.insert_text((x + 12, y + 18), label.upper(), fontsize=7, fontname='hebo', color=MUTED)
    page.insert_text((x + 12, y + 42), str(value), fontsize=17, fontname='hebo', color=NAVY)
    if note:
        page.insert_text((x + width - 12 - min(len(note) * 4, width / 2), y + 42), note, fontsize=7, color=MUTED)


def _draw_overview(document, analytics, generated_by):
    session = analytics['session']
    page = _header(document, 'Post-Lesson Engagement Report')
    generated = timezone.localtime().strftime('%b %d, %Y at %I:%M %p')
    page.insert_text((MARGIN, 112), f"{session['subject_code']} - {session['subject_name']}", fontsize=20, fontname='hebo', color=NAVY)
    page.insert_text((MARGIN, 134), f"Classroom {session['classroom']}  |  {session['teacher_name']}  |  {session['session_date']}", fontsize=9, color=MUTED)
    page.insert_text((PAGE_WIDTH - 250, 112), f'Generated by {generated_by.get_full_name() or generated_by.username}', fontsize=8, color=MUTED)
    page.insert_text((PAGE_WIDTH - 250, 128), generated, fontsize=8, color=MUTED)

    _section_title(page, 166, 'Session Summary')
    summary = analytics['summary']
    card_width = (PAGE_WIDTH - MARGIN * 2 - 20) / 3
    values = [
        ('Students Detected', summary['students_detected'], 'peak count'),
        ('Session Duration', _duration(session['duration_seconds']), f"{session['slides_covered']} slides"),
        ('Average Engagement', _percent(summary['average_engagement']), 'engaged'),
        ('Total Detections', summary['total_detections'], 'all samples'),
        ('Average Confidence', _percent(summary['average_confidence']), 'weighted'),
        ('Session Status', session['status'].title(), ''),
    ]
    for index, (label, value, note) in enumerate(values):
        x = MARGIN + (index % 3) * (card_width + 10)
        y = 180 + (index // 3) * 72
        _summary_card(page, x, y, card_width, label, value, note)

    _section_title(page, 340, 'Engagement Distribution')
    if analytics['has_data']:
        for index, category in enumerate(CATEGORIES):
            y = 363 + index * 25
            value = analytics['distribution'][category]
            page.insert_text((MARGIN, y + 9), category.title(), fontsize=8, color=NAVY)
            bar_x = MARGIN + 88
            bar_width = 250
            page.draw_rect(pymupdf.Rect(bar_x, y, bar_x + bar_width, y + 10), color=LIGHT, fill=LIGHT)
            page.draw_rect(
                pymupdf.Rect(bar_x, y, bar_x + bar_width * value / 100, y + 10),
                color=CATEGORY_COLORS[category],
                fill=CATEGORY_COLORS[category],
            )
            page.insert_text((bar_x + bar_width + 10, y + 9), _percent(value), fontsize=8, color=MUTED)

        insights = analytics['insights']
        insight_x = 470
        page.insert_text((insight_x, 371), 'KEY INSIGHTS', fontsize=8, fontname='hebo', color=BRAND)
        lines = [
            f"Highest engagement: Slide {insights['highest_engagement']['slide_number']} ({_percent(insights['highest_engagement']['percentage'])})",
            f"Most confusion: Slide {insights['most_confusion']['slide_number']} ({_percent(insights['most_confusion']['percentage'])})",
            f"Most disengaged: Slide {insights['most_disengaged']['slide_number']} ({_percent(insights['most_disengaged']['percentage'])})",
        ]
        for index, line in enumerate(lines):
            page.insert_text((insight_x, 397 + index * 24), line, fontsize=9, color=NAVY)
        page.insert_textbox(
            pymupdf.Rect(insight_x, 470, PAGE_WIDTH - MARGIN, 530),
            insights['recommendation'],
            fontsize=8,
            color=MUTED,
        )
    else:
        page.draw_rect(pymupdf.Rect(MARGIN, 360, PAGE_WIDTH - MARGIN, 440), color=(0.87, 0.9, 1), fill=(0.96, 0.97, 1))
        page.insert_text((MARGIN + 18, 389), 'No engagement data was recorded for this session.', fontsize=12, fontname='hebo', color=NAVY)
        page.insert_text((MARGIN + 18, 414), 'Session timing and slide activity remain available in the breakdown.', fontsize=9, color=MUTED)


def _draw_slide_table(document, analytics):
    columns = [
        ('Slide', 35), ('Topic', 180), ('Time', 70), ('Duration', 62), ('Detected', 58),
        ('Engaged', 62), ('Attentive', 62), ('Confused', 62), ('Bored', 52), ('Disengaged', 70),
    ]
    rows_per_page = 13
    slides = analytics['slides'] or [None]
    for offset in range(0, len(slides), rows_per_page):
        page = _header(document, 'Post-Lesson Engagement Report')
        _section_title(page, 112, 'Slide-by-Slide Breakdown')
        y = 132
        x = MARGIN
        page.draw_rect(pymupdf.Rect(MARGIN, y, PAGE_WIDTH - MARGIN, y + 26), color=NAVY, fill=NAVY)
        for label, width in columns:
            page.insert_text((x + 5, y + 17), label.upper(), fontsize=6.5, fontname='hebo', color=WHITE)
            x += width
        y += 26
        for slide in slides[offset:offset + rows_per_page]:
            page.draw_rect(pymupdf.Rect(MARGIN, y, PAGE_WIDTH - MARGIN, y + 29), color=(0.91, 0.93, 0.96))
            if slide is None:
                page.insert_text((MARGIN + 8, y + 19), 'No slide activity was recorded.', fontsize=8, color=MUTED)
                break
            entered = timezone.localtime(datetime.fromisoformat(slide['entered_at'])).strftime('%I:%M %p')
            values = [
                slide['slide_number'], slide['title'][:36], entered, _duration(slide['duration_seconds']),
                slide['detected'] if slide['has_data'] else 'N/A', _percent(slide['engaged']),
                _percent(slide['attentive']), _percent(slide['confused']), _percent(slide['bored']),
                _percent(slide['disengaged']),
            ]
            x = MARGIN
            for value, (_, width) in zip(values, columns):
                page.insert_text((x + 5, y + 19), str(value), fontsize=7, color=NAVY)
                x += width
            y += 29


def generate_pdf(analytics, generated_by):
    document = pymupdf.open()
    _draw_overview(document, analytics, generated_by)
    _draw_slide_table(document, analytics)
    for page_number, page in enumerate(document, start=1):
        page.draw_line((MARGIN, PAGE_HEIGHT - 25), (PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 25), color=(0.9, 0.92, 0.95))
        page.insert_text((MARGIN, PAGE_HEIGHT - 10), 'TAGAD - Classroom Engagement Analytics', fontsize=7, color=MUTED)
        page.insert_text((PAGE_WIDTH - 82, PAGE_HEIGHT - 10), f'Page {page_number}', fontsize=7, color=MUTED)
    content = document.tobytes(garbage=4, deflate=True)
    document.close()
    return content


def generate_report_content(session, report_type, generated_by):
    analytics = build_session_analytics(session, previous_session=_previous_session(session))
    if report_type == 'pdf':
        return generate_pdf(analytics, generated_by)
    return analytics_csv_content(analytics).encode('utf-8')


def report_storage_name(session, report_type):
    return f'reports/{session.pk}/{uuid4().hex}.{report_type}'
