from django.urls import path

from .views import (
    CameraDetailView,
    CameraListCreateView,
    ClassManagementOptionsView,
    ClassroomDetailView,
    ClassroomListCreateView,
    DashboardSummaryView,
    CsrfView,
    CurrentUserView,
    LoginView,
    LogoutView,
    RegistrationView,
    SubjectDetailView,
    SubjectListCreateView,
    UserDetailView,
    UserListCreateView,
    UserOptionsView,
)
from .session_views import (
    PresentationDetailView,
    PresentationListCreateView,
    PresentationPreviewView,
    PresentationSlideImageView,
    PresentationSourceView,
    SessionEndView,
    SessionEnterSlideView,
    SessionListCreateView,
    SessionOptionsView,
)


urlpatterns = [
    path('csrf/', CsrfView.as_view(), name='csrf'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('me/', CurrentUserView.as_view(), name='current-user'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('users/', UserListCreateView.as_view(), name='user-list'),
    path('users/options/', UserOptionsView.as_view(), name='user-options'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('classrooms/', ClassroomListCreateView.as_view(), name='classroom-list'),
    path('classrooms/<int:pk>/', ClassroomDetailView.as_view(), name='classroom-detail'),
    path('subjects/', SubjectListCreateView.as_view(), name='subject-list'),
    path('subjects/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
    path('class-management/options/', ClassManagementOptionsView.as_view(), name='class-management-options'),
    path('cameras/', CameraListCreateView.as_view(), name='camera-list'),
    path('cameras/<int:pk>/', CameraDetailView.as_view(), name='camera-detail'),
    path('dashboard/', DashboardSummaryView.as_view(), name='dashboard-summary'),
    path('presentations/', PresentationListCreateView.as_view(), name='presentation-list'),
    path('presentations/<int:pk>/', PresentationDetailView.as_view(), name='presentation-detail'),
    path('presentations/<int:pk>/source/', PresentationSourceView.as_view(), name='presentation-source'),
    path('presentations/<int:pk>/preview/', PresentationPreviewView.as_view(), name='presentation-preview'),
    path(
        'presentations/<int:pk>/slides/<int:slide_pk>/image/',
        PresentationSlideImageView.as_view(),
        name='presentation-slide-image',
    ),
    path('session-options/', SessionOptionsView.as_view(), name='session-options'),
    path('sessions/', SessionListCreateView.as_view(), name='session-list'),
    path('sessions/<int:pk>/end/', SessionEndView.as_view(), name='session-end'),
    path(
        'sessions/<int:pk>/enter-slide/',
        SessionEnterSlideView.as_view(),
        name='session-enter-slide',
    ),
]
