"""
Django settings for tagad project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'core',
]

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    'core.authentication.EmailOrUsernameBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.tagad_exception_handler',
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default=(
        'http://localhost:5173,http://127.0.0.1:5173,'
        'http://localhost:5174,http://127.0.0.1:5174'
    ) if DEBUG else '',
    cast=Csv(),
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ActiveUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tagad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tagad.wsgi.application'
ASGI_APPLICATION = 'tagad.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

ENABLE_PIPELINE_SIMULATOR = config('ENABLE_PIPELINE_SIMULATOR', default=False, cast=bool)
PIPELINE_API_KEY = config('PIPELINE_API_KEY', default='')
ENGAGEMENT_ALERT_CONSECUTIVE_WINDOWS = config(
    'ENGAGEMENT_ALERT_CONSECUTIVE_WINDOWS', default=3, cast=int,
)
PIPELINE_HEARTBEAT_TIMEOUT_SECONDS = config(
    'PIPELINE_HEARTBEAT_TIMEOUT_SECONDS', default=10, cast=int,
)
TAGAD_YOLO_MODEL_PATH = config(
    'TAGAD_YOLO_MODEL_PATH', default='model_artifacts/tagad_yolo11_head_v2_best.pt',
)
TAGAD_FACE_LANDMARKER_PATH = config(
    'TAGAD_FACE_LANDMARKER_PATH', default='model_artifacts/face_landmarker.task',
)
TAGAD_STATE_MODEL_PATH = config(
    'TAGAD_STATE_MODEL_PATH',
    default='model_artifacts/tagad_state_svm_rich_threshold1_candidate.joblib',
)
TAGAD_ATTENTION_MODEL_PATH = config(
    'TAGAD_ATTENTION_MODEL_PATH',
    default='model_artifacts/dipser_attention_10-feature_diagnostic.joblib',
)
TAGAD_MODEL_PIPELINE_VERSION = config('TAGAD_MODEL_PIPELINE_VERSION', default='hierarchical-1')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': config('DB_CONNECT_TIMEOUT_SECONDS', default=5, cast=int),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        },
    },
    {
        'NAME': 'core.validators.CharacterMixValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT_SECONDS', default=3600, cast=int)
LOGIN_THROTTLE_MAX_FAILURES = config('LOGIN_THROTTLE_MAX_FAILURES', default=5, cast=int)
LOGIN_THROTTLE_CLIENT_MAX_FAILURES = config(
    'LOGIN_THROTTLE_CLIENT_MAX_FAILURES', default=25, cast=int,
)
LOGIN_THROTTLE_WINDOW_SECONDS = config(
    'LOGIN_THROTTLE_WINDOW_SECONDS', default=900, cast=int,
)
LOGIN_THROTTLE_BLOCK_SECONDS = config(
    'LOGIN_THROTTLE_BLOCK_SECONDS', default=900, cast=int,
)
PASSWORD_RESET_THROTTLE_MAX_REQUESTS = config(
    'PASSWORD_RESET_THROTTLE_MAX_REQUESTS', default=3, cast=int,
)
PASSWORD_RESET_THROTTLE_CLIENT_MAX_REQUESTS = config(
    'PASSWORD_RESET_THROTTLE_CLIENT_MAX_REQUESTS', default=15, cast=int,
)
PASSWORD_RESET_THROTTLE_WINDOW_SECONDS = config(
    'PASSWORD_RESET_THROTTLE_WINDOW_SECONDS', default=900, cast=int,
)
PASSWORD_RESET_THROTTLE_BLOCK_SECONDS = config(
    'PASSWORD_RESET_THROTTLE_BLOCK_SECONDS', default=900, cast=int,
)
TRUSTED_PROXY_COUNT = config('TRUSTED_PROXY_COUNT', default=0, cast=int)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='TAGAD <noreply@localhost>')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
PRESENTATION_MAX_UPLOAD_BYTES = config(
    'PRESENTATION_MAX_UPLOAD_BYTES',
    default=50 * 1024 * 1024,
    cast=int,
)
PRESENTATION_MAX_EXPANDED_BYTES = config(
    'PRESENTATION_MAX_EXPANDED_BYTES',
    default=250 * 1024 * 1024,
    cast=int,
)
PRESENTATION_MAX_SLIDES = config('PRESENTATION_MAX_SLIDES', default=300, cast=int)
LIBREOFFICE_PATH = config('LIBREOFFICE_PATH', default='')
PG_DUMP_PATH = config('PG_DUMP_PATH', default='')
PG_RESTORE_PATH = config('PG_RESTORE_PATH', default='')
POSTGRES_TOOL_TIMEOUT_SECONDS = config('POSTGRES_TOOL_TIMEOUT_SECONDS', default=300, cast=int)
DATABASE_BACKUP_ROOT = BASE_DIR / config('DATABASE_BACKUP_DIRECTORY', default='backups')

# R6 retention policy. Cleanup is opt-in and dry-runs unless --execute is used.
RETENTION_FAILED_PRESENTATION_DAYS = config(
    'RETENTION_FAILED_PRESENTATION_DAYS', default=30, cast=int,
)
RETENTION_REPORT_DAYS = config('RETENTION_REPORT_DAYS', default=365, cast=int)
RETENTION_ENGAGEMENT_SUMMARY_DAYS = config(
    'RETENTION_ENGAGEMENT_SUMMARY_DAYS', default=180, cast=int,
)
RETENTION_SYSTEM_LOG_DAYS = config('RETENTION_SYSTEM_LOG_DAYS', default=180, cast=int)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Operational logs are structured, redacted, and rotated locally. Production
# deployments can replace these handlers with their centralized log collector.
LOG_DIRECTORY = BASE_DIR / 'logs'
LOG_DIRECTORY.mkdir(parents=True, exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {'()': 'core.observability.RequestContextFilter'},
    },
    'formatters': {
        'safe_json': {'()': 'core.observability.SafeJsonFormatter'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': config('LOG_CONSOLE_LEVEL', default='WARNING'),
            'filters': ['request_context'],
            'formatter': 'safe_json',
        },
        'rotating_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'level': config('LOG_FILE_LEVEL', default='INFO'),
            'filters': ['request_context'],
            'formatter': 'safe_json',
            'filename': LOG_DIRECTORY / 'tagad.log',
            'maxBytes': config('LOG_MAX_BYTES', default=5 * 1024 * 1024, cast=int),
            'backupCount': config('LOG_BACKUP_COUNT', default=5, cast=int),
            'encoding': 'utf-8',
            'delay': True,
        },
    },
    'loggers': {
        'tagad': {
            'handlers': ['console', 'rotating_file'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}
