# Generated by Django 5.2.15 on 2026-07-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subject_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
