# Generated by Django 5.2.15 on 2026-07-11 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='classroomsession',
            name='classroom',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=30, unique=True)),
                ('subject_name', models.CharField(max_length=150)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.subject'),
            preserve_default=False,
        ),
    ]
