# Generated by Django 5.2.15 on 2026-09-07 15:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_camera_constraints_and_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentationslide',
            options={'ordering': ('slide_number',)},
        ),
        migrations.AddField(
            model_name='presentation',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='presentation',
            name='preview_path',
            field=models.FileField(blank=True, max_length=500, upload_to=core.models.presentation_preview_path),
        ),
        migrations.AddField(
            model_name='presentation',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file_path',
            field=models.FileField(max_length=500, upload_to=core.models.presentation_upload_path),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='total_slides',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presentationslide',
            name='image_path',
            field=models.FileField(blank=True, max_length=500, upload_to=core.models.presentation_slide_path),
        ),
        migrations.AddConstraint(
            model_name='classroomsession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_active_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='presentationslide',
            constraint=models.UniqueConstraint(fields=('presentation', 'slide_number'), name='presentation_slide_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessioncamera',
            constraint=models.UniqueConstraint(fields=('session', 'camera'), name='session_camera_unique'),
        ),
    ]
