# Generated by Django 5.2.15 on 2026-09-22 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_presentation_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementsummary',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_engagement_summaries', to='core.camera'),
        ),
        migrations.CreateModel(
            name='CameraWorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('starting', 'Starting'), ('online', 'Online'), ('reconnecting', 'Reconnecting'), ('offline', 'Offline'), ('stopped', 'Stopped')], max_length=20)),
                ('source_type', models.CharField(choices=[('simulated', 'Simulated'), ('live', 'Live')], max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('', 'None'), ('processing', 'Processing'), ('source_unavailable', 'Source unavailable'), ('read_failed', 'Stream interrupted'), ('retry_exhausted', 'Retry limit reached'), ('heartbeat_stale', 'Heartbeat is stale'), ('session_ended', 'Session ended'), ('shutdown', 'Controller stopped')], max_length=30)),
                ('pipeline_version', models.CharField(max_length=50)),
                ('analysis_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('yolo_candidates', models.PositiveIntegerField(default=0)),
                ('valid_faces', models.PositiveIntegerField(default=0)),
                ('confirmed_students', models.PositiveIntegerField(default=0)),
                ('unclassified_students', models.PositiveIntegerField(default=0)),
                ('latest_counts', models.JSONField(default=dict)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_statuses', to='core.camera')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_worker_statuses', to='core.classroomsession')),
            ],
            options={
                'db_table': 'camera_worker_statuses',
                'indexes': [models.Index(fields=['session', 'last_heartbeat'], name='camera_worker_session_hb')],
                'constraints': [models.UniqueConstraint(fields=('session', 'camera'), name='camera_worker_session_camera_unique')],
            },
        ),
    ]
